version: '3.1'
services:
  db:
    image: mysql
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
    - "3306:3306"
    volumes:
      - /var/mysql-data:/var/lib/mysql